name: OldDeploy Orchestrator

on:
  push:
    branches:
      - main  # Adjust this to your main branch name if different.

  workflow_dispatch: # Manual trigger with environment selection.
    inputs:
      environment:
        description: 'Environment.'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  old_deploy_to_dev:
    if: github.event.inputs.environment == 'dev'
    uses: ./.github/workflows/old-deploy_to_dev.yml
    secrets: inherit
    with:
      environment: ${{ github.event.inputs.environment }}

  old_deploy_to_prod:
    if: github.event.inputs.environment == 'prod'
    uses: ./.github/workflows/old-deploy_to_prod.yml
    secrets: inherit
    with:
      environment: ${{ github.event.inputs.environment }}