name: Action One

on:
  workflow_call:
    inputs:
      env:
        description: 'Environment'
        required: true
        type: string

jobs:
  dummy_job_one:
    runs-on: ubuntu-latest
    steps:
      - name: Print Environment from Action One
        run: echo "Running Action One in ${{ inputs.env }}"
