name: Action One

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to run the actions (dev, dev2, prod)'
        required: true
        default: 'dev'
        type: string

jobs:
  dummy_job_one:
      runs-on: ubuntu-latest
      steps:
        - name: Print Environment from Action One
          run: echo "Running Action One in ${{ inputs.environment }}"

