name: Action One

on:
  workflow_call:
    secrets:
      env:
        required: true

jobs:
  dummy_job_one:
      runs-on: ubuntu-latest
      steps:
        - name: Print Environment from Action One
          run: echo "Running Action One in${{ secrets.env }}"

