on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: string

jobs:
  dummy_job_one:
    runs-on: ubuntu-latest
    steps:
      - name: Print Environment from Action One
        run: echo "Running Workflow One "
