name: Deploy artifacts

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      environment: ${{ steps.set_output.outputs.environment }}
      workflow: ${{ steps.set_output.outputs.workflow }}
    steps:
      - name: Dummy deploy data
        id: set_output
        run: |
          echo "::set-output name=environment::dev"
          echo "::set-output name=workflow::all"
