name: Deploy artifacts

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Dummy deploy data
        run: |
          echo "Dummy deploy action"

  trigger_orchestrator:
    needs: deploy
    uses: ./.github/workflows/restart-orchestrator.yml
    with:
      workflow: 'all'
      environment: 'dev'
#    secrets: inherit
