name: Deploy artifacts

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Dummy deploy data
        run: |
          echo "Dummy deploy action"

      - name: Output data
        id: set_output
        run: | 
         echo "::set-output name=environment::dev"
         echo "::set-output name=workflow::all"
    outputs:
      environment: ${{ steps.set_output.outputs.environment }}
      workflow: ${{ steps.set_output.outputs.workflow }}

#  trigger_orchestrator:
#    uses: ./.github/workflows/restart-orchestrator.yml
#    with:
#      workflow: 'all'
#      environment: 'dev'
