name: Deploy Orchestrator

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy_to_dev:
    if: ithub.event_name == 'push'
    uses: ./.github/workflows/deploy_to_dev.yml
    secrets: inherit
    with:
      environment: 'push_action=dev'

  deploy_to_prod:
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/deploy_to_prod.yml
    secrets: inherit
    with:
      environment: 'manual_trigger=prod'

