name: Deploy to Dev

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: 'string'
env:
  VAR_FROM_VARS: ${{vars.TEST_VAR}}

jobs:
  deploy_to_dev:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Print Environment From Deploy to Dev
        run: |
         echo "Running Deploy to:${{ inputs.environment }}"
         echo "Running Deploy with ENV: $VAR_FROM_VARS"