name: Restart Admin

on:
  workflow_call:
    inputs:
      workflow:
        description: 'Workflow'
        required: true
        type: 'string'
      environment:
        description: 'Environment'
        required: true
        type: 'string'


jobs:
  restart-admin:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Print vars and secrets
        run: |
          echo "This is variable: ${{ vars.TEST_VAR  }}"
          echo "This is secret: ${{ secrets.TEST_SECRET }}"
          echo "Current environment:${{ inputs.environment }}"
          echo "Current workflow:${{ inputs.workflow }}"