name: Restart Admin in main package

on:
  workflow_call:

jobs:
  restart-admin:
    runs-on: ubuntu-latest
    steps:
      - name: Print vars and secrets
        run: |
          echo "This is variable: ${{ vars.TEST_VAR  }}"
          echo "This is secret: ${{ secrets.TEST_SECRET }}"