name: Restart Frontend

on:
  workflow_call:

jobs:
  restart-frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Print vars and secrets
        run: |
          echo "This is variable: ${{ vars.TEST_VAR  }}"
          echo "This is secret: ${{ secrets.TEST_SECRET }}"
          echo "Current environment:${{ github.event.inputs.environment }}"
          echo "Current workflow:${{ github.event.inputs.workflow }}"